### ISSUE TITLE
 Why there is no rotating function

### ISSUE THREAD

**Issue by longtaoge** [IsseiAoki/SimpleCropView#10]
SimpleCropView is Very nice and good !

Why there is no rotating function
   like 
  https://github.com/edmodo/cropper ’s 
 cropImageView.rotateImage(ROTATE_NINETY_DEGREES);
simetimes this is It is necessary.

**Comment by IsseiAoki** [comment]
Thank you @longtaoge .
Version 1.0.8 has been released.
SimpleCropView now supports image rotation.
