### ISSUE TITLE
Can we save crop positions for image and later use over that image again

### ISSUE THREAD

**Issue by corientdev** [IsseiAoki/SimpleCropView#107]
Can we save crop positions for image and later use over that image again?

I believe it should be there but not documented.

**Comment by corientdev** [comment]
I believe we can get the positions by using `getActualCropRect`

What about reapplying to the image in cropview?

**Comment by corientdev** [comment]
I believe we can get rectangle using `getActualCropRect` but how about reapplying this to selection of the same image?

**Comment by IsseiAoki** [comment]
@corientdev 
Version 1.1.5 has been released. 
CropImageView now supports save/restore frame rect.

Usage is below...

* Save FrameRect
```
RectF mFrameRect;

mFrameRect = mCropView.getActualCropRect()
```
* Restore FrameRect
```
mCropView.load(result.getData())
         .initialFrameRect(mFrameRect)
         .execute(mLoadCallback);
```
See also the sample project.
