### ISSUE TITLE
Issue on Android N

### ISSUE THREAD

**Issue by arunrajgm** [IsseiAoki/SimpleCropView#111]
https://github.com/IsseiAoki/SimpleCropView/pull/102
Why this is closed without merging?
i am getting error using android N version.
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 20195964 bytes
Please look on this

**Comment by IsseiAoki** [comment]
In the new version, CropImageView does not save bitmap internally . Please use the version 1.1.5 and see also new sample.
