### ISSUE TITLE
Bugs in api level higher than 23

### ISSUE THREAD

**Issue by igreenwood** [IsseiAoki/SimpleCropView#124]
* `context.getContentResolver().openInputStream` throws `FileNotFoundException`.(That worked in 23.)
* Needs investigation for changes related to Uris in new apis(24~26).

**Comment by igreenwood** [comment]
It seems like an emulator bug.

**Comment by i3130002** [comment]
> It seems like an emulator bug.

@IsseiAoki 

That would be great if you push a fix for that

**Comment by i3130002** [comment]
According to [link]( https://stackoverflow.com/a/6228188/1454173) you'd better not to use url to path.
I was able to load image using this code (instead of cropView.load(uri).execute(null) )
```
InputStream input;
Bitmap bmp;
try {
    input = getApplicationContext().getContentResolver().openInputStream(img);
    bmp = BitmapFactory.decodeStream(input);
    cropImageView.setImageBitmap(bmp);
} catch (FileNotFoundException e1) {
    e1.printStackTrace();
}
```

So I suggest to replace load method getting parameter context and fix the issue
