### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sergeyfitis** [IsseiAoki/SimpleCropView#14]
Hi. Can I get cropped region coordinates?

**Comment by IsseiAoki** [comment]
Hi, @sergeyfitis.

SimpleCropView does not provide public method to get cropped region coordinates.
`private RectF mFrameRect` in `CropImageView.java` is the cropped region coordinates.

**Comment by xzchaoo** [comment]
If you really want, you can use reflect.

**Comment by IsseiAoki** [comment]
@sergeyfitis 

Hi,

Version 1.0.9 has been released.
I added `getActualCropRect()`

You can use it : )

**Comment by sergeyfitis** [comment]
@IsseiAoki Thank very much :) :+1:

**Comment by corientdev** [comment]
How to reapply the coordinates to the loaded image?
