### ISSUE TITLE
Question: Can we crop with circle but save as a square?

### ISSUE THREAD

**Issue by KaLingCode** [IsseiAoki/SimpleCropView#16]
HI, 

This is what I am trying to do, I want to let user cropped the image with the Circle at the same time I want to send to Square version to the sever.

**Comment by xzchaoo** [comment]
You can find some extra process in CropImageView.getCroppedBitmap().
At first, I used:
```java
civ.setCropMode(CropImageView.CropMode.RATIO_1_1);
iv.setImageBitmap(civ.getCroppedBitmap());//want to get a square
civ.setCropMode(CropImageView.CropMode.CIRCLE);//restore
```
But this will reset the frame rect to center.
I have to use reflect.
```java
try {
	Field f = civ.getClass().getDeclaredField("mCropMode");
	f.setAccessible(true);
	f.set(civ, CropImageView.CropMode.RATIO_1_1);
} catch (Exception e) {
	//ignore
}

iv.setImageBitmap(civ.getCroppedBitmap());//want to get a square

try {
	Field f = civ.getClass().getDeclaredField("mCropMode");
	f.setAccessible(true);
	f.set(civ, CropImageView.CropMode.CIRCLE);//restore
} catch (Exception e) {
	//ignore
}
```

**Comment by IsseiAoki** [comment]
@KaLingCode 

Hi, 

Version 1.0.8 has been released.
I added `getRectBitmap()`. 

You can use it  : )

**Comment by ryanjohn1** [comment]
If anyone comes back to this later as I did, this is now achieved by setting the crop mode to CropImageView.CropMode.CIRCLE_SQUARE
It shows a circular crop guide but saves as a square
