### ISSUE TITLE
Rotate image

### ISSUE THREAD

**Issue by tuhin10** [IsseiAoki/SimpleCropView#2]
Is there any way to rotate the image??

**Comment by abist** [comment]
You can use the exif data to rotate the image. Here's how to do it - http://stackoverflow.com/questions/20478765/how-to-get-the-correct-orientation-of-the-image-selected-from-the-default-image

**Comment by IsseiAoki** [comment]
Sorry...SimpleCropView does not support image rotation.
You can use the exif data as abist say.

**Comment by IsseiAoki** [comment]
Version 1.0.8 has been released.
SimpleCropView now supports image rotation.
