### ISSUE TITLE
IllegalArgumentException when cropping certain size image

### ISSUE THREAD

**Issue by gcrescent** [IsseiAoki/SimpleCropView#20]
Hi,

I got this error message whenever I'm trying to crop 1200 x 1200px (or its multiply 2400 x 2400 etc) image. 
java.lang.IllegalArgumentException: y + height must be <= bitmap.height()
            at android.graphics.Bitmap.createBitmap(Bitmap.java:669)
            at com.isseiaoki.simplecropview.CropImageView.getCroppedBitmap(CropImageView.java:1012)

I called getCroppedBitmap() without resize the image (moving the handle)

I'm using:
cropMode="ratio_1_1"
handleSize="12dp"
minFrameSize="200dp"
initialFrameScale="1.0"

Can you help me? Thank you

**Comment by IsseiAoki** [comment]
Hi, 

Sorry...i'm investigating the issue.
Please send me your sample project or the corresponding image file, if you don't mind.
 
i.greenwood.dev@gmail.com

Thank you

**Comment by gcrescent** [comment]
Hi,
I have sent you an email last week, have you find out what is wrong? Thanks

**Comment by IsseiAoki** [comment]
Hi,

Sorry for late response.
Thank you for sending the sample project.
The cause is rounding error of the frame position.
I fixed the bug and released new version. 
Please use version 1.0.10.
Thank you for finding a bug : )

**Comment by gcrescent** [comment]
Thank you! It's working great now :D
