### ISSUE TITLE
final bitmap minimum pixel size

### ISSUE THREAD

**Issue by piphagor** [IsseiAoki/SimpleCropView#27]
It would be helpful to set min size of final cropped bitmap in pixels.

**Comment by IsseiAoki** [comment]
Hi,

I'm so sorry!!
I thought I had merged your PR(#28), but I could not found your code when I checked the source code today. So I re-added your code manually from your PR. 
Please use version 1.0.13.

**Comment by piphagor** [comment]
Hi,

Actually, I asked for **cropped bitmap** minimum pixel size. Method setMinFrameSizeInPx() sets size for frame and cropped bitmap may be of any size, dependent on scale. Thats why I deleted my PR. Thats not resolving my problem. 

Now I added some logic to set proper frame size in my project, but it looks not very cool, it will be very convenient to have such method in your library.

P.S. Anyway, your lib helps me a lot. Thanks.
