### ISSUE TITLE
Jar version

### ISSUE THREAD

**Issue by bambolz** [IsseiAoki/SimpleCropView#32]
is there any jar version for this library? because of some limitation I unable to use gradle in my projects, thanks

**Comment by IsseiAoki** [comment]
Hi,

Sorry, SimpleCropView not provides jar version.
But you can use SimpleCropView by copying the following files to your project : )

simplecropview/src/main/java/com/isseiaoki/simplecropview/CropImageView.java
simplecropview/src/main/res/values/attrs_crop_image_view.xml

**Comment by bambolz** [comment]
it works, 
many thanks :)
