### ISSUE TITLE
Just crop the Image displayed in the ImageView?

### ISSUE THREAD

**Issue by gordonpro** [IsseiAoki/SimpleCropView#35]
Sometimes, You want to crop an large picture, it may be 8000x6000, And then, App use a Loader such as picasso to display a thumbnail image to the ImageView to prevent OutOfMemory crash. Maybe, a 400x300 picture to displayed in the ImageView. Then cropping of the image is not cropping to the original image, in other words, it cannot get a cropped image to original picture..

**Comment by khafan** [comment]
I'm facing same issue. A little googling and I found <a href=BitmapRegionDecoder> BitmapRegionDecoder</a> but it arises a new problem! - Reading from different sources which picasso was handling nicely.

**Comment by MrVilkaman** [comment]
@khafan https://github.com/IsseiAoki/SimpleCropView/issues/BitmapRegionDecoder not found =(

**Comment by khafan** [comment]
@MrVilkaman I know it's late but Anyway, sorry for silly mistake. Fixed the url

**Comment by IsseiAoki** [comment]
Hi,

Sorry for late response.
Version 1.1.0 has been released.
SimpleCropView now supports large size image : )
Please try sample!
