### ISSUE TITLE
handleSize is too large

### ISSUE THREAD

**Issue by wl386123298** [IsseiAoki/SimpleCropView#36]
how to custom the handleSize,  it's too large！

**Comment by 18611480882** [comment]
+1

**Comment by baji841** [comment]
in Activity you can set through below line
cropImageView.setHandleSizeInDp(  size in integers );

**Comment by wl386123298** [comment]
no use, the handSize's default value is 8dp！！！

**Comment by wl386123298** [comment]
3Q
