### ISSUE TITLE
photo is dark

### ISSUE THREAD

**Issue by arash-jahani** [IsseiAoki/SimpleCropView#37]
![device-2015-12-06-155848](https://cloud.githubusercontent.com/assets/2876900/11613319/4b1c8a12-9c32-11e5-8f33-55d62a616c32.png)

use big size image
res:5000*2000
size=5mb

**Comment by MrVilkaman** [comment]
+1 I have similar issue when I try crop photo on sumsung S4 with max photo resolution 4128x3096, 3 mb
I also noticed on the screen of display memory usage graph (in android studio)  rises steeply! for photo ~ 3 mb graphite jumped ~ +40 mb

**Comment by arash-jahani** [comment]
@MrVilkaman  I got my problem solved by this :
cropImageView.setImageBitmap(Bitmap.createScaledBitmap(BitmapFactory.decodeStream(getContentResolver().openInputStream(picUri)), 1800, 1200, true));

**Comment by MrVilkaman** [comment]
@arash-jahani Yes, I have done in a similar way! But I would like that the library has taken a decision on this problems!

**Comment by jatempa** [comment]
I use this library in combination with Picasso library for solve it

**Comment by Spierki** [comment]
I think it's not an error of the library, if you look at your log you will see : 
OpenGLRenderer: Bitmap too large to be uploaded into a texture

This is why when you resize the image you can display it

**Comment by iRYO400** [comment]
Mby it's OpenGL's restrictions. but, how Sony's developers bypassed that. Here is I'm cropping 8K image.
![screenshot_2016-03-17-21-53-28](https://cloud.githubusercontent.com/assets/12654767/13852087/da7d38d4-ec8a-11e5-82a5-aafb63ab7c49.png)

**Comment by IsseiAoki** [comment]
Hi,
Sorry for late response.
SimpleCropView now supports large size image loading/cropping.
Please use version 1.1.0.

**Comment by iRYO400** [comment]
@IsseiAoki Hi mate!
So, the maximum is 4096x4096?
