### ISSUE TITLE
please remove "<application android:label="@string/app_name">"

### ISSUE THREAD

**Issue by Rainer-Lang** [IsseiAoki/SimpleCropView#38]
Error:Execution failed for task ':app:processDevDebugManifest'.
> Manifest merger failed : Attribute application@label value=(@string/XYZ) from AndroidManifest.xml:74:9-40
	is also present at [com.isseiaoki:simplecropview:1.0.13] AndroidManifest.xml:11:18-50 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:71:5-374:19 to override.

**Comment by IsseiAoki** [comment]
Hi, 

Thank you for your PR.
I merged your PR and updated.
