### ISSUE TITLE
Ability to set initial size and position of the frame?

### ISSUE THREAD

**Issue by baieric** [IsseiAoki/SimpleCropView#4]
I would like to have the frame be the full size of the image initially, or even some custom size and position.

**Comment by IsseiAoki** [comment]
Sorry...the initial position of the frame is not supported for now, but I'll think about it.

The way to customize the initial position of the frame is followings.

1. Copy SimpleCropView.java & attr_crop_image_view.xml to your project.

2. Modify the line 780 in the SimpleCropView.java

from
```
    mFrameRect = new RectF(l + w/8, t + h/8, r - w/8, b - h/8);
```
to
```
    mFrameRect = new RectF(l, t, r, b);
```

I hope this helps.

**Comment by IsseiAoki** [comment]
Version 1.0.8 has been released.
SimpleCropView now supports initial frame size.

**Comment by mostafaolyai** [comment]
> Version 1.0.8 has been released.
> SimpleCropView now supports initial frame size.

How can i set custom size?
