### ISSUE TITLE
setImageUrl

### ISSUE THREAD

**Issue by tymin** [IsseiAoki/SimpleCropView#45]
there is something wrong with setImageUrl.

**Comment by ay1man4** [comment]
Yes. If we use setImageURI the image not fit inside the view, instead it stretching out of the view!

**Comment by pepijntb** [comment]
Had the same. Probably and error in ImageView.
Work-a-round:
`cropper.setImageBitmap(BitmapFactory.decodeStream(getContext().getContentResolver().openInputStream(imageUri)));`
