### ISSUE TITLE
Error:(596) Attribute "backgroundColor" has already been defined

### ISSUE THREAD

**Issue by iRYO400** [IsseiAoki/SimpleCropView#47]
How to solve it?

**Comment by IsseiAoki** [comment]
Hi,

`backgroundColor` is defined in `attrs_crop_image_view.xml`.
If you are using the same name attribute in your project, please consider changing your attribute name.
If you are using the library that is using the same name attribute, I don't know how to solve it. 

See link below
https://groups.google.com/forum/#!topic/adt-dev/HeM0aptfddY

I am considering use custom unique prefix for all custom attributes or override predefined atribute in the Android Framework for the next version.

**Comment by BrightYu** [comment]
```
<attr name="backgroundColor" format="color" />

<declare-styleable name="SimpleCropView">
        <attr name="backgroundColor" />
</declare-styleable>
```

attr need like this

**Comment by iRYO400** [comment]
@IsseiAoki 
I've found reason why it gives error. It's because I use this library https://github.com/michelelacorte/ElasticProgressBar
I will try just copy these files into project as local https://github.com/IsseiAoki/SimpleCropView/tree/master/simplecropview/src/main
Mby tomorrow

**Comment by IsseiAoki** [comment]
@iRYO400 
That's a great idea!
I think it will work.

**Comment by iRYO400** [comment]
@IsseiAoki yahoooo! 
It works! 
And I have another question. 
How it crops the images? Does it with cropping decrease pixels count? 
For example, I want cut 3840x2160 image for half, and I will get 1920x2160 in the output, will It? 
I ask about this because I found another Crop library but it decrease pixels count from 16K image to 1K, when I cropped only half part.
Thanks. Sry for my English

**Comment by IsseiAoki** [comment]
@iRYO400 
For now, SimpleCropView uses the image that has set in ImageView in cropping. 
So, if the source image has scaled at the stage of `setImageBitmap()`,
the cropped image is also scaled. (SimpleCropView does not have the information about the real size of the image file.)

I know, it isn't smart. (I didn't know `BitmapRegionRecorder` when I released this library.)
I will take care of it as soon as possible.
Please wait for the next release. m(__)m

**Comment by iRYO400** [comment]
@IsseiAoki,
I tested it and it works as I want. 
It doesn't lose pixels after cropping.

Look at this library, it has some functions, that would be interest to you https://github.com/Yalantis/uCrop
And it also has big minus, after cropping image loses about >75% of pixels

**Comment by IsseiAoki** [comment]
@iRYO400 
I'm glad to hear that : )
Thank you for giving me a useful information.
