### ISSUE TITLE
imageRatio is calculated incorrectly with FREE as cropMode

### ISSUE THREAD

**Issue by mblcdr** [IsseiAoki/SimpleCropView#55]
in getRatioX() and getRatioY(), FREE mode is not taken into account. So in scaleBitmapIfNeeded(Bitmap) the value of imageRatio will always be 1.0 in FREE mode, which results in a loss of aspect ratio in scaled bitmap.

**Comment by IsseiAoki** [comment]
Hi,

Sorry, I will fix it as soon as possible.

**Comment by IsseiAoki** [comment]
I have fixed the bug. Please use the version 1.1.2.
Thank you for telling me about my bug : )

**Comment by mblcdr** [comment]
Thank you for taking time fixing this bug. Will test ASAP.
