### ISSUE TITLE
Migrating from old version

### ISSUE THREAD

**Issue by ubarua123** [IsseiAoki/SimpleCropView#66]
I have your older version of the library and those did not have the ` mCropView.startCrop` and ` mCropView.startLoad` methods. Also i developed it around where I pass the absolute path to the file and load it in the `CropImageView  bitmap`. 
Since you have introduced the `uri` model, is it mandatory to use this? 
Its going be quite tough to convert all the logic to uri based.

**Comment by IsseiAoki** [comment]
Hi,


Sorry for late response.
`uri` model is added for preventing OOM error in loading and cropping process.
If you do not handle large size bitmap for cropping, you can use `getCroppedBitmap()` as before.
