### ISSUE TITLE
Cropped image been cached after use

### ISSUE THREAD

**Issue by yomiolatunji** [IsseiAoki/SimpleCropView#67]
After cropping the first image, other attempt to crop other images return the first image cropped, until the app is restarted.

**Comment by IsseiAoki** [comment]
Hi,
Sorry for late response.

Actually, I did not observe a phenomenon at that time. 
I will investigate the problem and fix it as soon as possible. 
I'm developing this library in personal time alone, so it may take a little while. Sorry...

**Comment by IsseiAoki** [comment]
Hi,

I'm investigating this issue, but I cannot replicate the phenomenon.
What version are you using?
If possible, please send me a minimal sample project that replicates the phenomenon.

**Comment by XinyueZ** [comment]
The bug is reproduced, must be fixed.

**Comment by IsseiAoki** [comment]
Thank you for reporting. I will fix it for next version.

**Comment by vaniakerer** [comment]
Hi, @IsseiAoki,  I have same problem, but i fix it by changing createSaveUri() method:

   private Uri createSaveUri() {
        Uri outputUri = null;
            try {
                String ext = ".jpg";

                outputUri = Uri.fromFile(File.createTempFile("cropped", ext, getCacheDir()));
            } catch (IOException e) {
                throw new RuntimeException("Failed to create temp file for output image", e);
            }
        return outputUri;
    }

**Comment by IsseiAoki** [comment]
@vaniakerer Thank you!!! The bug is now fixed in the new sample.
