### ISSUE TITLE
NullPointException in Utils.getExifOrientation()

### ISSUE THREAD

**Issue by legendmohe** [IsseiAoki/SimpleCropView#68]
```
public static int getExifOrientation(Context context, Uri uri) {
        String authority = uri.getAuthority().toLowerCase();
        int orientation;
        if (authority.endsWith("media")) {
            orientation = getExifRotation(context, uri);
        } else {
            orientation = getExifRotation(getFileFromUri(context, uri));
        }
        return orientation;
    }
```
uri.getAuthority() == null will cause NullPointException. For example: Uri "/storage/emulated/0/homerun/homerun-Pictures/IMG_20160615_075035.jpg"

**Comment by IsseiAoki** [comment]
Hi,
Sorry for late response.

Actually, I did not observe a phenomenon at that time. 
I will investigate the problem and fix it as soon as possible. 
I'm developing this library in personal time alone, so it may take a little while. Sorry...

**Comment by legendmohe** [comment]
I'm not sure if it's a bug. 
I fix this with `Uri.fromFile(new File(thumbnailPath))` not 'Uri.parse(thumbnailPath)'
