### ISSUE TITLE
crop outputUri File  greater than source File ,why？

### ISSUE THREAD

**Issue by star95** [IsseiAoki/SimpleCropView#69]
use startCrop(createSaveUri(), mCropCallback, mSaveCallback);

**Comment by IsseiAoki** [comment]
Hi,
Sorry for late response.

Actually, I did not observe a phenomenon at that time. 
I will investigate the problem and fix it as soon as possible. 
I'm developing this library in personal time alone, so it may take a little while. Sorry...

**Comment by IsseiAoki** [comment]
Hi,

I'm investigating this issue, but I cannot replicate the phenomenon.
What version are you using?
If possible, please send me a minimal sample project that replicates the phenomenon.

**Comment by star95** [comment]
@IsseiAoki 
I took your latest demo，change Uri.fromFile(new File(getActivity().getExternalCacheDir(), "cropped"))
File dir， the discovery Android/data/com.example.simplecropviewsample/cache/cropped the cropped file is  greater than source File .

**Comment by IsseiAoki** [comment]
@star95 
I think it related to EXIF data. 
For now, SimpleCropView cannot set EXIF data correctly to cropped file.
Please move source file and cropped file to your computer and check file size.
