### ISSUE TITLE
Adjust the image to crop in the area of ​​cropimageview

### ISSUE THREAD

**Issue by Vierco** [IsseiAoki/SimpleCropView#73]
Hello,
Is there any way to adjust the image to crop in the area of ​​cropimageview?
android:adjustViewBounds="true" and android:scaleType="centerInside" don´t work.

Thanks for your awesome work

**Comment by IsseiAoki** [comment]
Hi,

In CropImageView, the image is scaled to fit the size of the view by maintaining the aspect ratio. WRAP_CONTENT will be ignored.
So, you don't need to use `adjustViewBounds=true` and `scaleType`. 
Is there anything wrong with that ?

**Comment by Vierco** [comment]
Thanks for your answer.
No problem, now, i understand how it´s work.

Thanks again!

Cheers :)
