### ISSUE TITLE
CropImageView SavedState takes too much space and crashes

### ISSUE THREAD

**Issue by GrindingOgre** [IsseiAoki/SimpleCropView#82]
Be careful on the CropImageView.onSaveInstanceState, because if i use a big bitmap, there's a chance that the app crashes.

I have CropImageView inside a fragment, and, when the app goes in background, it throws TransactionTooLargeException.
I've seen on onSaveInstanceState method that you save the bitmap inside the Bundle and i don't think this is a good practice.

To avoid this crash, i call setImageDrawable(null) when the Fragment goes inside onPause method

**Comment by Rainer-Lang** [comment]
@GrindingOgre I have the same problem. Do you have a solution?

**Comment by Nuclominus** [comment]
@Rainer-Lang you may create fast-fix like say @GrindingOgre.
1. Call mCropView.setImageDrawable(null) in onPause methode on MainFragment
2. Move setImageResource image from onViewCreated to onResume.

**Comment by GrindingOgre** [comment]
I used the same workaround as @Nuclominus and it worked just fine. Just don't use Glide or Picasso because there are some weird behaviour on some devices, like bitmap inside the view was overly scaled.

Unfortunately i had to switch to another library because this one didn't have all the features i need.

**Comment by IsseiAoki** [comment]
In the new version, CropImageView does not save bitmap internally . Please use the version 1.1.5 and see also new sample.
