### ISSUE TITLE
Significant increase in size

### ISSUE THREAD

**Issue by Vierco** [IsseiAoki/SimpleCropView#84]
I have found that when an image is cropped, the size automatically increases.
This has been reported previously in issues #78, but no response.
Someone may say something about it?

**Comment by IsseiAoki** [comment]
Hello, Sergio.

Thank you for your mail.
I'm sorry for that I haven't been maintaining so much recently.

I want to be helpful to you, but unfortunately I can't replicate the bug in my environment now.
Could you describe more details, or send me the project that replicates the problem?
Best regards.

**Comment by Vierco** [comment]
Thank you very much for your quick response.
Of course, I will prepare a project where the increased size of the bitmap
is replicated.
The current project is for a client and can not send full.

Thank you very much for your interest :)

Saludos / Best regards

*Sergio Alvarez*
email: sergioalvarezb@gmail.com
twitter: @Vierco


2016-10-17 15:45 GMT+02:00 Issei Aoki <notifications@github.com>:

**Comment by borjaMorilla** [comment]
It's true,  i have the same problem. For example,  I download a image  of 17KB  and I crop this image, after the image is of 100 KB.

Thanks !

> Sorry if my english isn't very good.

**Comment by Nicrob64** [comment]
@borjaMorilla 

Are you changing the compression format? 
(Downloading a jpg and then saving to png?)
That could cause an increase in size, going from a lossy to a lossless. 

It could also be due to downloading a low quality jpg and saving it at jpg quality 100.
Try fiddling with those options and see if it fixes your issue
